package mvcmessaging;

import javax.swing.*;
import java.util.*;
import com.mrjaffesclass.apcs.messages.*;

/**
 * Main view consists of a JFrame.  The subpanels are JPanels that are
 * inserted in the JFrame by dragging and dropping them from the Project
 * navigator window into the interface design window of the JFrame.  Much
 * of the code in this class is generated by the NetBeans GUI interface
 * and should not be changed.  This view will also instantiate the two 
 * subviews.
 * 
 * @author Roger
 * @version 2014-10-02
 */
public class AppView extends javax.swing.JFrame {

  /**
   * Creates new form AppView
   */
  public AppView() {
    initComponents();
  }
  
  /**
   * Getter for the left panel view
   * @return Right panel view
   */
  public LeftPanelView getLeftPanelView() {
    return leftPanelView1;
  }

  /**
   * Getter for the right panel view
   * @return Right panel view
   */
  public RightPanelView getRightPanelView() {
    return rightPanelView1;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    leftPanelView1 = new mvcmessaging.LeftPanelView();
    rightPanelView1 = new mvcmessaging.RightPanelView();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    leftPanelView1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(leftPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rightPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(leftPanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(rightPanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private mvcmessaging.LeftPanelView leftPanelView1;
  private mvcmessaging.RightPanelView rightPanelView1;
  // End of variables declaration//GEN-END:variables
}
