package com.mrjaffesclass.apcs.mvc.template.twowindow;

/**
 * Main view consists of a JFrame.  The subpanels are JPanels that are
 * inserted in the JFrame by dragging and dropping them from the Project
 * navigator window into the interface design window of the JFrame.  
 * 
 * Any code with a gray background is generated by the NetBeans GUI interface
 * and must not be changed.  This view will also instantiate the two 
 * subviews as part of the NetBeans generated code
 * 
 * The main view has no components and so doesn't need to send or receive messages.
 * Therefore no message object is saved in this class.
 * 
 * @author Roger
 * @version 2014-10-02
 */
public class AppView extends javax.swing.JFrame {

  /**
   * Creates new form AppView
   */
  public AppView() {
    initComponents();
  }
  
  /**
   * Getter function for the left panel
   * @return the leftPanelView
   */
  public LeftPanelView getLeftPanelView() {
    return leftPanelView1;
  }
  
  /**
   * Getter function for the right panel
   * @return the rightPanelView
   */
  public RightPanelView getRightPanelView() {
    return rightPanelView1;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    leftPanelView1 = new com.mrjaffesclass.apcs.mvc.template.twowindow.LeftPanelView();
    rightPanelView1 = new com.mrjaffesclass.apcs.mvc.template.twowindow.RightPanelView();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(leftPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rightPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(leftPanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(rightPanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.mrjaffesclass.apcs.mvc.template.twowindow.LeftPanelView leftPanelView1;
  private com.mrjaffesclass.apcs.mvc.template.twowindow.RightPanelView rightPanelView1;
  // End of variables declaration//GEN-END:variables
}
